### ISSUE TITLE
RECORDED SEQUENCE RBOT DATASET

### ISSUE THREAD

**Issue by thomCastillo** [DLR-RM/3DObjectTracking#10]
We ran the evaluate part of the code on the RBOD dataset, and the results were as in the article. But we could not run the RBOT dataset on https://github.com/DLR-RM/3DObjectTracking/blob/master/RBGT/examples/run_on_recorded_sequence.cpp, we couln't render the objects, what should we do for this, is there a parameter we need to change?

**Comment by rohanscryenx** [comment]
> We ran the evaluate part of the code on the RBOD dataset, and the results were as in the article. But we could not run the RBOT dataset on https://github.com/DLR-RM/3DObjectTracking/blob/master/RBGT/examples/run_on_recorded_sequence.cpp, we couln't render the objects, what should we do for this, is there a parameter we need to change?

Hey, were you able to solve the above issue. If yes then can yo please provide the required steps. I am also trying to run the same file but when I run it I get some errors including some missing files like color_camera_meta_data.txt, body_1.txt, body_2.txt. Here's a [link](https://github.com/DLR-RM/3DObjectTracking/issues/11) to my the detailed explanation of my issue. Any kind of help would be useful, thanks in advance.
