### ISSUE TITLE
Working codebase or implementation of this repo?

### ISSUE THREAD

**Issue by rohang1411** [DLR-RM/3DObjectTracking#12]
Can someone please provide a working codebase or implementation of this repo. Coz I really need it. I'm trying to build something similar and unable to run the present code.

**Comment by samuelmorais** [comment]
Hi, @rohang1411 I ported this code to Mac and iOS, but it is a private solution, and I can't share it publicly.

But what I can say is that it can run on 20 fps on iPhone 12 and the only issue I have is the initialization workflow, which requires some practice and can be difficult for new users.
