### ISSUE TITLE
Where can I find your paper

### ISSUE THREAD

**Issue by Steven0928** [DLR-RM/3DObjectTracking#18]
Hi，
    Where can i find your paper?

**Comment by chuandalijie** [comment]
you can find the paper in here.
https://openaccess.thecvf.com/content/ACCV2020/papers/Stoiber_A_Sparse_Gaussian_Approach_to_Region-Based_6DoF_Object_Tracking_ACCV_2020_paper.pdf

**Comment by manuel-stoiber** [comment]
In addition to the ACCV paper, the paper for SRT3D and ICG are both available on arXiv:
- https://arxiv.org/abs/2110.12715
- https://arxiv.org/abs/2203.05334
