### ISSUE TITLE
How to generate .bin file

### ISSUE THREAD

**Issue by 2640546445** [DLR-RM/3DObjectTracking#19]
I'm a novice, and although your code is commented in important places, I still don't know how to generate .bin files. Which executable file should I run? I look forward to your reply

**Comment by manuel-stoiber** [comment]
In the most recent version of the code (ICG), .bin files are automatically generated by the `RegionModel` and `DepthModel` if they do not exist. The best starting point is probably `examples/run_on_camera_sequence.cpp`. In this example, generated .bin files are stored in the specified `directory`.

**Comment by 2640546445** [comment]
Thank you for your reply. With your help, the problem has been solved
