### ISSUE TITLE
Using a depth camera (such as ENSENSO) that does not have an RGB camera

### ISSUE THREAD

**Issue by wwh01875** [DLR-RM/3DObjectTracking#23]
I want to use the ENSENSO_N35 depth camera to use this algorithm. It uses a binocular grayscale image camera to identify the depth. I would like to ask if the part that requires RGB in this algorithm only has grayscale images, is it feasible?
And if I want to modify the program to apply the ENSENSO_N35 camera, what components need to be repaired?
thanks

**Comment by manuel-stoiber** [comment]
The developed `RegionModality` class only supports RGB images. In theory, the code can also be adapted to support grayscale images. However, note that the 1D color space of grayscale images contains significantly less information than the 3D color space of RGB images. Depending on your application, using color statistics of grayscale images alone might not be sufficient to differentiate between the object and background region.
