### ISSUE TITLE
No Depth in run_on_recorded_sequence.cpp

### ISSUE THREAD

**Issue by peymoon** [DLR-RM/3DObjectTracking#25]
Is there any reason that the run_on_recorded_sequence.cpp only uses color camera and not depth?
I added the depth components back to the code (same as run_on_camera_sequence.cpp). But it does not seem to change anything

**Comment by manuel-stoiber** [comment]
There is no particular reason. `run_on_recorded_sequence.cpp` is just an example that shows one possible tracker configuration. Feel free to modify it to suit your needs.
