### ISSUE TITLE
No information or file regarding the color_camera_meta_data.txt

### ISSUE THREAD

**Issue by Mahendra-ajnlens** [DLR-RM/3DObjectTracking#26]
I was running for my own datasets using the run_on_recorded_sequence..I could see that there was a input named color_camera_meta_data.txt
I could not see in the repo nor in the original dataset.
Can you please explain me the format or provide a sample file.
It would highly benefit me.
Thanks

**Comment by manuel-stoiber** [comment]
Which version of the code are you referring to?
For ICG, which is the latest version, parameters for cameras are stored in YAML files. The content of those files is defined in the readme:
```
load_directory: "./"
intrinsics:
   f_u: 638.633
   f_v: 638.377
   pp_x: 639.451
   pp_y: 366.379
   width: 1280
   height: 720
camera2world_pose: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [ 1., 0., 0., 0.,
            0., 1., 0., 0.,
            0., 0., 1., 0.,
            0., 0., 0., 1. ]
depth_scale: 0.001    # only for depth camera
image_name_pre: "color_camera_image_"
load_index: 0
n_leading_zeros: 0
image_name_post: ""
load_image_type: "png"
```
- `load_directory`: directory from which images are loaded.
- `intrinsics`: intrinsics of the camera that was used to record images, with fu, fv, ppu, ppv, width, and height, respectively.
- `depth_scale`: scale with which pixel values have to be multiplied to get the depth in meter. (only required for depth cameras)
- `image_name_pre`: text at the beginning of image name, before load_index.
- `load_index`: index of the first image that is loaded.
- `n_leading_zeros`: minimum number of digits used in the image name with zero padding to reach correct number.
- `image_name_post`: text at the end of image name, after load_index.
- `load_image_type`: file format of images.

**Comment by Mahendra-ajnlens** [comment]
Thanks for your input.
Also how to track on custom dataset like LINEMOD.
Can you please suggest what changes needs to be incorporated?

**Comment by manuel-stoiber** [comment]
Unfortunately, *LINEMOD* does not provide continuous sequences. Continuous tracking is therefore not possible. Although, one can of course evaluate individual frames and random pose differences similar to:

*Tan, David Joseph, Nassir Navab, and Federico Tombari. "Looking beyond the simple scenarios: Combining learners and optimizers in 3D temporal tracking." IEEE transactions on visualization and computer graphics 23.11 (2017): 2399-2409.*

In general, as a start, I would suggest to look at the *evaluator* classes (*ycb_evaluator*, *opt_evaluator*, ...) in the *examples* folder.
