### ISSUE TITLE
Can I use a simple RGB camera not the rgbd?

### ISSUE THREAD

**Issue by timeanddoctor** [DLR-RM/3DObjectTracking#27]
Can I use a simple RGB camera not the rgbd?

**Comment by manuel-stoiber** [comment]
Yes, you can use the tracker without depth information.

**Comment by timeanddoctor** [comment]
Thank you very much. Professor manuel-stoiber.
I compiled the [SRT3D](https://github.com/DLR-RM/3DObjectTracking/tree/master/SRT3D)  with my friends. But I still can not open the camera with the [run_on_camera_sequence.exe](https://github.com/DLR-RM/3DObjectTracking/blob/master/SRT3D/examples/run_on_camera_sequence.cpp).  
Can you help me edite the camera class for a RGB camera. Thanks. https://github.com/timeanddoctor/3DObjectTracking?organization=timeanddoctor&organization=timeanddoctor

**Comment by TrinhNC** [comment]
How can I run ICG without using the depth information or it is the same as just running SRT3D?
