### ISSUE TITLE
random vs uniform sampling

### ISSUE THREAD

**Issue by teigl** [DLR-RM/3DObjectTracking#28]
What is the reasoning behind randomly sampling contour points? My initial thought would be uniform sampling.
Great work btw!

**Comment by manuel-stoiber** [comment]
The main reason is that random sampling allows to define the number of used points after the sparse viewpoint model is generated (as long as the number is smaller than the number of sampled points). For uniform sampling, the model would have to be generated every time the number of points is changed. However, in general, uniform sampling is also be possible.

**Comment by teigl** [comment]
Ok thanks!
