### ISSUE TITLE
I am having issues making a reference point in ICG for Manual Detection.

### ISSUE THREAD

**Issue by happyiminjay1** [DLR-RM/3DObjectTracking#29]
Is there any guideline to get reference points?

Thanks.

**Comment by manuel-stoiber** [comment]
Reference points can be any distinguishable points on the object for which you know the 3D coordinates. Typical examples are object corners. During manual detection, you need to select those points in the RGB image. The detector is then able to compute the 6DoF pose.

**Comment by TrinhNC** [comment]
I tried this manual detector but still could not make it work. After selecting 4 points on the image, the program just stopped. Do you have any ideas why? The 3D coordinates were selected in Meshlab and I assumed they are correct.
