### ISSUE TITLE
A ROS wrapper for ICG

### ISSUE THREAD

**Issue by zhangbaozhe** [DLR-RM/3DObjectTracking#31]
Hey guys, I've been following your work for quite a long time. Recently, one of our projects uses your library and I've been writing a ROS wrapper. The first version of the wrapper is not well-written. The second one [HERE](https://github.com/zhangbaozhe/icg_ros) can work well. 

I am still reading your papers, (though it's a little bit hard since I am new to this field). Anyway, just posting the wrapper here in case someone else needs to use this library with ROS.

**Comment by manuel-stoiber** [comment]
Hey @zhangbaozhe, thank you very much for your work and that you made the code publicly available! I am sure it will be very helpful for many people who use ROS.
