### ISSUE TITLE
Histograms could not be initialised for modality body1_region_modality

### ISSUE THREAD

**Issue by Hamdi-Ben-Abdallah** [DLR-RM/3DObjectTracking#33]
Hello,

Do you know the reason for the "Histograms could not be initialised for modality body1_region_modality" error message?

Thank you in advance

**Comment by manuel-stoiber** [comment]
Probably, when modalities are started and histograms are initialized, your body is outside of the camera image. As a consequence, it is not possible to initialize. You have to provide a valid initial pose using, for example, a `Detector` on your body.
