### ISSUE TITLE
Visualizing correspondence lines?

### ISSUE THREAD

**Issue by MedericFourmy** [DLR-RM/3DObjectTracking#34]
Hello,

Thank you for sharing your code, ICG worked out of the box for me with a Realsense and a cheezit box.
Would it be possible to visualize correspondence lines as shown in the paper accompanying video?
Thanks

EDIT: found Tracker::VisualizeCorrespondences

**Comment by manuel-stoiber** [comment]
Yes, you can visualize correspondence lines using the parameter `visualize_lines_correspondence` for the `RegionModality`. This results in correspondence lines being visualized for each iteration.
Also, for the `Tracker`, you can define the `visualization_time`. If you set it to `0`, you can manually step through images.
