### ISSUE TITLE
Problem when using  3DObjectTracking/ICG as a subdirectory 

### ISSUE THREAD

**Issue by MedericFourmy** [DLR-RM/3DObjectTracking#36]
Using ICG as an external dependency with `add_subdirectory` creates a compilation error. The problem comes from [these lines](https://github.com/DLR-RM/3DObjectTracking/blob/ef0b302feb41472c5974d47d5017f6920cae7cf6/ICG/CMakeLists.txt#L125) of ICG `CMakeLists.txt`. When using a ICG as a subdirectory, `CMAKE_SOURCE_DIR` has actually the path of the parent project which creates the issue.

Replacing these two lines with:
```
include_directories("include")
include_directories("third_party")
```
works fine in all the cases.
I can open a PR if you want.

**Comment by manuel-stoiber** [comment]
Thank you very much for the comment. I replaced it in the respective CMake file.
