### ISSUE TITLE
Tracking with multiple cameras

### ISSUE THREAD

**Issue by lishiyu005** [DLR-RM/3DObjectTracking#37]
Dear author,

I would like to track objects with two Azure kinect cameras. Is there a code example to show how to make a setup with multiple cameras?

Thank you very much. Great thanks in advance.

**Comment by kleinseben** [comment]
I have the same issue, did you solve it ?

**Comment by manuel-stoiber** [comment]
Unfortunately, the `AzureKinectCamera` class is currently designed as a singleton class that only supports a single physical Azure Kinect camera. If you want to use multiple Azure Kinect cameras you would have to adapt the source code of this class and the respective SetUp process.

Once you have created an implementation that supports multiply physical cameras, the process is relatively easy. Just set the `world2camera_pose` (or `camera2world_pose`) for each physical camera (note that depth and color cameras have different poses) based on relative poses from an external camera calibration. After that, define separate modalities for each camera and add them to the `Link` object.

**Comment by calmelo** [comment]
> Unfortunately, the `AzureKinectCamera` class is currently designed as a singleton class that only supports a single physical Azure Kinect camera. If you want to use multiple Azure Kinect cameras you would have to adapt the source code of this class and the respective SetUp process.
> 
> Once you have created an implementation that supports multiply physical cameras, the process is relatively easy. Just set the `world2camera_pose` (or `camera2world_pose`) for each physical camera (note that depth and color cameras have different poses) based on relative poses from an external camera calibration. After that, define separate modalities for each camera and add them to the `Link` object.

Hi, can you provide a code example for two realsense depth cameras? I want to use two depth cameras to increase the tracking range and I can't implement it. Excuse me, thanks!
