### ISSUE TITLE
Quality factor without ground truth?

### ISSUE THREAD

**Issue by dpuraj84** [DLR-RM/3DObjectTracking#39]
Is it possible to have some kind of quality factor to quantify if the object is being tracked accurately? For us, ground truth is not available all the time this means that we cannot calculate the ADD values. 

I was wondering if one could use your (from paper) Energy equation to calculate some kind of quality factor which can be just used as an indicator and not as a hard truth of a good object matching/tracking. 

Great job btw, really impressive and innovative work!! Thank you for this and thank you in advance for your kind help.

**Comment by paroj** [comment]
I think it is a major limitation of this work, that you actually cannot easily calculate a quality factor.

The relevant measures are implicitly available in the Hessian and gradient equations, but more work is needed to get to a quality "probability" from there..

**Comment by manuel-stoiber** [comment]
While it is not implemented, it would be straightforward to compute the joint probability. In general, all information for this is available in the `CalculateGradientAndHessian` methods of the region, depth, and texture modalities (for the region modality, just use the `data_line.distribution` value at 0, and for the depth and texture modalities compute the probability using `epsilon` or `error` together with the standard deviation values). Like for gradient vectors and Hessian matrices, one can compute the joint probability for each modality and later combine those values in the `Link` object.

In addition to using the joint probability as indicator for the tracking quality, one could of course also think about other factors, such as the percentage of measurements with a certain quality, etc. In general, I would encourage you to just play around with different options and see what works best.
