### ISSUE TITLE
Could you tell me how to derive these formulas

### ISSUE THREAD

**Issue by HMCCMH** [DLR-RM/3DObjectTracking#45]
This [Projection Matrix](https://github.com/DLR-RM/3DObjectTracking/blob/35c26c4c6582f4e9ea12b4ad285c7f760f64c588/ICG/src/renderer.cpp#L257) formula is different from the general OpenGL Projection Matrix. The z-axis values seem to be the negatives of the original values.

What's more, could you tell me how to get the [formula](https://github.com/DLR-RM/3DObjectTracking/blob/35c26c4c6582f4e9ea12b4ad285c7f760f64c588/ICG/src/renderer.cpp#L365)? 

Thanks!

**Comment by manuel-stoiber** [comment]
In our work, we use the common definition that the camera coordinate frame is right-handed and the x-axis points right, the y-axis downwards, and the z-axis away from the camera. This differs from the OpenGL definition, where the z-axis points towards the camera and the y-axis upwards. In addition, OpenGL uses the bottom left corner as (0,0), while OpenCV uses the top left corner. This results in the perceived differences in the projection matrix.

`r_u` is the maximum distance from the center of a sphere to the outer point of that sphere in image space along the u-axis. The sphere is thereby projected into the image and perspective projection is considered given that the sphere is located at `x`, `y`, `z`, and has a radius `r` in 3D space.
