### ISSUE TITLE
Timing execution

### ISSUE THREAD

**Issue by lmuffang** [DLR-RM/3DObjectTracking#7]
Hello,

In your amazing paper, it is specified that RBGT uses only a single thread. I was wondering if it is possible to optimize the execution time by doing some tasks in parallel. For example, I already tried to parallelize overall `region_modality_ptr` pointers when various bodies are tracked and it greatly reduces the execution time. For the update, I simply parallelized `CalculatePoseUpdate` over every `data_line` to save extra time and `CalculateCorrespondences` over every template view's data points. 
Is there is any other way to increase the execution time? Does the size of the tracked object have an influence on the timing?

I am using a laptop with an Intel i7 at 2.8GHz and I have between 50-70ms in execution time. This reduces the frame rate and the tracking is thus easily lost during fast motion due to large movements between frames.

Thanks for the help!

**Comment by huanghone** [comment]
The authors claim that the runtime is about 3ms per frame. Do you verify the runtime? Is that true?

**Comment by manuel-stoiber** [comment]
Having such a large execution time, there is probably some issue with your code modifications or your execution. Even on a modest laptop, we would expect an execution time way below 5ms for the tracking of a single object on a single CPU core.

The size of the object does not matter.
